/////////////////////////////////////////////////////////////////////////////
#ifndef DMDMH
#define DMDMH

#include <System.Classes.hpp>
#include <System.Win.ComServ.hpp>
#include <System.Win.ComObj.hpp>
#include <System.Win.VCLCom.hpp>
#include <Datasnap.DataBkr.hpp>
#include <Datasnap.DBClient.hpp>
#include <axbase.h>


#include <Data.DB.hpp>
#include <FireDAC.Comp.Client.hpp>
#include <FireDAC.Comp.DataSet.hpp>
#include <FireDAC.DApt.hpp>
#include <FireDAC.DApt.Intf.hpp>
#include <FireDAC.DatS.hpp>
#include <FireDAC.Phys.hpp>
#include <FireDAC.Phys.Intf.hpp>
#include <FireDAC.Phys.MSSQL.hpp>
#include <FireDAC.Phys.MSSQLDef.hpp>
#include <FireDAC.Stan.Async.hpp>
#include <FireDAC.Stan.Def.hpp>
#include <FireDAC.Stan.Error.hpp>
#include <FireDAC.Stan.Intf.hpp>
#include <FireDAC.Stan.Option.hpp>
#include <FireDAC.Stan.Param.hpp>
#include <FireDAC.Stan.Pool.hpp>
#include <FireDAC.UI.Intf.hpp>
#include <FireDAC.VCLUI.Wait.hpp>

#include "frxClass.hpp"
#include "frxDBSet.hpp"
#include "frxExportPDF.hpp"

#include "UMain.h"
#include "UnitCNT.h"
#include "UnitGRP.h"
#include "UnitINV.h"
#include "UnitLF.h"
#include "UnitLFITM.h"
#include "UnitASMITM.h"
#include "UnitSC.h"

class TDM : public TRemoteDataModule
{
__published:  // Composants gérés par l'EDI
	TDataSource *DCNT;
	TDataSource *DGRP;
	TDataSource *DITM;
	TFDTable *WITM;
	TFDTable *WGRP;
	TFDTable *WCNT;
	TFDTable *VLF_QTY;
	TLargeintField *VLF_QTYLF_ITM_ID;
	TLargeintField *VLF_QTYTotal;
	TFDTable *VITM_NEXT;
	TFDTable *WINVPAY;
	TFDTable *WASMITM;
	TDataSource *DASMITM;
	TDataSource *DASM;
	TDataSource *DLFITM;
	TDataSource *DPURPAY;
	TDataSource *DPURITM;
	TDataSource *DPUR;
	TDataSource *DSAL;
	TFDTable *TASMITM;
	TFDQuery *QREP_PUR;
	TLargeintField *QREP_PURPURITM_PUR_ID;
	TSQLTimeStampField *QREP_PURPUR_DATE;
	TWideStringField *QREP_PURCNT_FIRSTNAME;
	TWideStringField *QREP_PURCNT_LASTNAME;
	TCurrencyField *QREP_PURTotal;
	TDataSource *DREP_PUR;
	TFDQuery *QPAYPURTOT;
	TLargeintField *QPAYPURTOTPUR_ID;
	TCurrencyField *QPAYPURTOTTotal;
	TDataSource *DPAYPURTOT;
	TFDQuery *QHSTITMPUR;
	TDataSource *DHSTITMPUR;
	TDataSource *DHSTITMLF;
	TFDQuery *QHSTITMLF;
	TFDQuery *QHSTITMASM;
	TWideStringField *QHSTITMASMITM_CP;
	TLargeintField *QHSTITMASMITM_CODE;
	TWideStringField *QHSTITMASMITM_INDICE;
	TLargeintField *QHSTITMASMQty;
	TWideStringField *QHSTITMASMITM_NAME;
	TWideStringField *QHSTITMASMASM_COMMENT;
	TDateField *QHSTITMASMASM_DATE;
	TDataSource *DHSTITMASM;
	TDataSource *DHSTPURITM;
	TFDQuery *QHSTPURITM;
	TFDTable *WASM;
	TFDTable *WLFITM;
	TLargeintField *WGRPGRP_ID;
	TWideStringField *WGRPGRP_NAME;
	TWideStringField *WGRPGRP_COMMENT;
	TLargeintField *WITMITM_ID;
	TLargeintField *WITMITM_GRP_ID;
	TWideStringField *WITMITM_CP;
	TLargeintField *WITMITM_CODE;
	TWideStringField *WITMITM_INDICE;
	TWideStringField *WITMITM_NAME;
	TWideStringField *WITMITM_UNIT;
	TCurrencyField *WITMITM_PURCHASE;
	TCurrencyField *WITMITM_SALE;
	TWideStringField *WITMITM_COMMENT;
	TFDConnection *Connect;
	TFDTable *VPUR_NEXT;
	TLargeintField *VITM_NEXTNEXT;
	TLargeintField *VPUR_NEXTNEXT;
	TFDTable *WINV;
	TDataSource *DWGRP;
	TDataSource *DWITM;
	TFDTable *WINVITM;
	TLargeintField *WINVITMINVITM_INV_ID;
	TLargeintField *WINVITMINVITM_ITM_ID;
	TLargeintField *WINVITMINVITM_QTY;
	TWideStringField *WINVITMINVITM_COMMENT;
	TLargeintField *WINVITMINVITM_ID;
	TLargeintField *WPURITMINVITM_ID;
	TLargeintField *WPURITMINVITM_INV_ID;
	TLargeintField *WPURITMINVITM_ITM_ID;
	TWideStringField *WPURITMITM_CP;
	TLargeintField *WPURITMITM_CODE;
	TWideStringField *WPURITMITM_INDICE;
	TWideStringField *WPURITMITM_NAME;
	TLargeintField *WPURITMINVITM_QTY;
	TCurrencyField *WPURITMTotal;
	TWideStringField *WPURITMINVITM_COMMENT;
	TFDTable *WPURITM;
	TLargeintField *WINVINV_ID;
	TWideStringField *WINVINV_TYPE;
	TLargeintField *WINVINV_NUMBER;
	TSQLTimeStampField *WINVINV_DATE;
	TLargeintField *WINVINV_CNT_ID;
	TWideStringField *WINVINV_COMMENT;
	TWideStringField *WINVINV_STATUS;
	TCurrencyField *WINVITMINVITM_AMOUNT;
	TWideStringField *WINVITMINVITM_DELIVERY;
	TCurrencyField *WPURITMINVITM_AMOUNT;
	TWideStringField *WPURITMINVITM_DELIVERY;
	TLargeintField *WINVPAYINVPAY_ID;
	TLargeintField *WINVPAYINVPAY_INV_ID;
	TCurrencyField *WINVPAYINVPAY_AMOUNT;
	TSQLTimeStampField *WINVPAYINVPAY_DATE;
	TWideStringField *WINVPAYINVPAY_COMMENT;
	TLargeintField *QHSTITMPURINV_NUMBER;
	TLargeintField *QHSTITMPURINVITM_INV_ID;
	TCurrencyField *QHSTITMPURINVITM_AMOUNT;
	TLargeintField *QHSTITMPURINVITM_QTY;
	TLargeintField *QHSTITMPURITM_ID;
	TSQLTimeStampField *QHSTITMPURINV_DATE;
	TWideStringField *QHSTITMPURCNT_FIRSTNAME;
	TLargeintField *QHSTPURITMINVITM_QTY;
	TCurrencyField *QHSTPURITMINVITM_AMOUNT;
	TWideStringField *QHSTPURITMITM_CP;
	TLargeintField *QHSTPURITMITM_CODE;
	TWideStringField *QHSTPURITMITM_INDICE;
	TWideStringField *QHSTPURITMITM_NAME;
	TFDQuery *QHSTITMFROMASM;
	TWideStringField *QHSTITMFROMASMITM_CP;
	TLargeintField *QHSTITMFROMASMITM_CODE;
	TWideStringField *QHSTITMFROMASMITM_INDICE;
	TLargeintField *QHSTITMFROMASMASMITM_QTY;
	TWideStringField *QHSTITMFROMASMITM_NAME;
	TDataSource *DHSTITMFROMASM;
	TFDQuery *QHSTITMSAL;
	TDataSource *DHSTITMSAL;
	TLargeintField *QHSTITMSALINV_NUMBER;
	TLargeintField *QHSTITMSALINVITM_INV_ID;
	TCurrencyField *QHSTITMSALINVITM_AMOUNT;
	TLargeintField *QHSTITMSALINVITM_QTY;
	TLargeintField *QHSTITMSALITM_ID;
	TSQLTimeStampField *QHSTITMSALINV_DATE;
	TWideStringField *QHSTITMSALCNT_FIRSTNAME;
	TDataSource *DSALITM;
	TFDTable *TSALPAY;
	TCurrencyField *CurrencyField4;
	TWideStringField *WideStringField9;
	TDataSource *DSALPAY;
	TLargeintField *TSALPAYINVPAY_ID;
	TLargeintField *TSALPAYINVPAY_INV_ID;
	TFDTable *VSAL_NEXT;
	TLargeintField *VSAL_NEXTNEXT;
	TLargeintField *QHSTPURITMINVITM_ITM_ID;
	TFDConnection *Master;
	TLargeintField *TASMITMASMITM_ID;
	TLargeintField *TASMITMASMITM_ASM_ID;
	TLargeintField *TASMITMASMITM_QTY;
	TWideStringField *TASMITMASMITM_COMMENT;
	TWideStringField *TASMITMITM_CP;
	TLargeintField *TASMITMITM_CODE;
	TWideStringField *TASMITMITM_INDICE;
	TWideStringField *TASMITMITM_NAME;
	TWideStringField *TASMITMITM_COMMENT;
	TCurrencyField *TASMITMITM_PURCHASE;
	TCurrencyField *TASMITMITM_SALE;
	TLargeintField *TASMITMASMITM_ITM_ID;
	TLargeintField *WASMITMASMITM_ID;
	TLargeintField *WASMITMASMITM_ASM_ID;
	TLargeintField *WASMITMASMITM_ITM_ID;
	TLargeintField *WASMITMASMITM_QTY;
	TWideStringField *WASMITMASMITM_COMMENT;
	TfrxReport *ReportItem;
	TfrxDBDataset *frxDBITM;
	TfrxDBDataset *frxDBSAL;
	TfrxDBDataset *frxDBSALITM;
	TfrxReport *ReportSAL;
	TfrxDBDataset *frxDBSALPAY;
	TDataSource *DPROFIT;
	TFDQuery *QDAY_INV_ITM;
	TWideStringField *QDAY_INV_ITMITM_CP;
	TLargeintField *QDAY_INV_ITMITM_CODE;
	TWideStringField *QDAY_INV_ITMITM_INDICE;
	TLargeintField *QDAY_INV_ITMINVITM_QTY;
	TCurrencyField *QDAY_INV_ITMITM_PURCHASE;
	TCurrencyField *QDAY_INV_ITMINVITM_AMOUNT;
	TCurrencyField *QDAY_INV_ITMPurtotal;
	TCurrencyField *QDAY_INV_ITMSaltotal;
	TCurrencyField *QDAY_INV_ITMProfit;
	TSQLTimeStampField *QDAY_INV_ITMINV_DATE;
	TLargeintField *QDAY_INV_ITMITM_ID;
	TLargeintField *QDAY_INV_ITMINVITM_ID;
	TLargeintField *QDAY_INV_ITMINV_ID;
	TLargeintField *QDAY_INV_ITMINV_NUMBER;
	TWideStringField *QDAY_INV_ITMITM_NAME;
	TWideStringField *QDAY_INV_ITMCNT_FIRSTNAME;
	TLargeintField *QDAY_INV_ITMCNT_ID;
	TfrxDBDataset *frxDBProfit;
	TfrxReport *Report_DAY_INV_ITM;
	TIntegerField *QDAY_INV_ITMYY;
	TIntegerField *QDAY_INV_ITMMM;
	TfrxReport *Report_YY_MM_INV;
	TFDQuery *QYY_MM_INV;
	TLargeintField *QYY_MM_INVINV_NUMBER;
	TWideStringField *QYY_MM_INVCNT_FIRSTNAME;
	TCurrencyField *QYY_MM_INVPUR;
	TCurrencyField *QYY_MM_INVSAL;
	TCurrencyField *QYY_MM_INVPRO;
	TLargeintField *QYY_MM_INVINV_ID;
	TIntegerField *QYY_MM_INVYY;
	TIntegerField *QYY_MM_INVMM;
	TfrxDBDataset *frxDBSUMPROFIT;
	TSQLTimeStampField *QYY_MM_INVINV_DATE;
	TfrxReport *Report_YY_MM;
	TFDManager *FDManager1;
	TfrxReport *ReportPUR;
	TFDQuery *QTODO_NEG;
	TFDQuery *QTODO_UNK;
	TFDQuery *QTODO_SALDLV;
	TDataSource *DSTODO_NEG;
	TDataSource *DSTODO_UNK;
	TLargeintField *QTODO_SALDLVITM_CODE;
	TWideStringField *QTODO_SALDLVITM_CP;
	TWideStringField *QTODO_SALDLVITM_INDICE;
	TWideStringField *QTODO_SALDLVITM_NAME;
	TLargeintField *QTODO_SALDLVINVITM_QTY;
	TDataSource *DSTODO_SALDLV;
	TWideStringField *QTODO_SALDLVCNT_FIRSTNAME;
	TFDQuery *QTODO_PURDLV;
	TDataSource *DSTODO_PURDLV;
	TWideStringField *QTODO_PURDLVITM_CP;
	TLargeintField *QTODO_PURDLVITM_CODE;
	TWideStringField *QTODO_PURDLVITM_INDICE;
	TWideStringField *QTODO_PURDLVITM_NAME;
	TLargeintField *QTODO_PURDLVINVITM_QTY;
	TWideStringField *QTODO_PURDLVCNT_FIRSTNAME;
	TFDQuery *QTODO_SALPAY;
	TDataSource *DSTODO_SALPAY;
	TLargeintField *QTODO_SALPAYINV_NUMBER;
	TSQLTimeStampField *QTODO_SALPAYINV_DATE;
	TCurrencyField *QTODO_SALPAYDue;
	TWideStringField *QTODO_SALPAYCNT_FIRSTNAME;
	TDataSource *DSTODO_PURPAY;
	TFDQuery *QTODO_PURPAY;
	TLargeintField *QTODO_PURPAYINV_NUMBER;
	TWideStringField *QTODO_PURPAYCNT_FIRSTNAME;
	TSQLTimeStampField *QTODO_PURPAYINV_DATE;
	TCurrencyField *QTODO_PURPAYDue;
	TfrxDBDataset *frxDBPUR;
	TfrxDBDataset *frxDBPURITM;
	TfrxDBDataset *frxDBPURPAY;
	TSQLTimeStampField *TSALPAYINVPAY_DATE;
	TFDQuery *TITM;
	TWideStringField *TITMITM_CP;
	TLargeintField *TITMITM_CODE;
	TWideStringField *TITMITM_INDICE;
	TWideStringField *TITMGRP_NAME;
	TWideStringField *TITMITM_NAME;
	TWideStringField *TITMITM_UNIT;
	TCurrencyField *TITMITM_PURCHASE;
	TCurrencyField *TITMITM_SALE;
	TLargeintField *TITMPUR;
	TLargeintField *TITMSAL;
	TLargeintField *TITMLF;
	TLargeintField *TITMASM;
	TLargeintField *TITMUSED;
	TLargeintField *TITMStock;
	TWideStringField *TITMITM_COMMENT;
	TLargeintField *TITMITM_ID;
	TLargeintField *TITMITM_GRP_ID;
	TFDQuery *TLFITM;
	TWideStringField *TLFITMITM_CP;
	TLargeintField *TLFITMITM_CODE;
	TWideStringField *TLFITMITM_INDICE;
	TWideStringField *TLFITMITM_NAME;
	TWideStringField *TLFITMGRP_NAME;
	TCurrencyField *TLFITMITM_PURCHASE;
	TCurrencyField *TLFITMITM_SALE;
	TLargeintField *TLFITMPUR;
	TLargeintField *TLFITMSAL;
	TLargeintField *TLFITMASM;
	TLargeintField *TLFITMUSED;
	TLargeintField *TLFITMStock;
	TLargeintField *TLFITMGRP_ID;
	TFDQuery *TSALITM;
	TLargeintField *TSALITMINVITM_ID;
	TLargeintField *TSALITMINVITM_INV_ID;
	TLargeintField *TSALITMINVITM_ITM_ID;
	TWideStringField *TSALITMITM_CP;
	TLargeintField *TSALITMITM_CODE;
	TWideStringField *TSALITMITM_INDICE;
	TWideStringField *TSALITMITM_NAME;
	TCurrencyField *TSALITMINVITM_AMOUNT;
	TLargeintField *TSALITMINVITM_QTY;
	TCurrencyField *TSALITMTotal;
	TWideStringField *TSALITMINVITM_COMMENT;
	TWideStringField *TSALITMINVITM_DELIVERY;
	TCurrencyField *TSALITMITM_PURCHASE;
	TCurrencyField *TSALITMITM_SALE;
	TCurrencyField *TSALITMProfit;
	TFDQuery *TPURITM;
	TLargeintField *TPURITMINVITM_ID;
	TLargeintField *TPURITMINVITM_INV_ID;
	TLargeintField *TPURITMINVITM_ITM_ID;
	TWideStringField *TPURITMITM_CP;
	TLargeintField *TPURITMITM_CODE;
	TWideStringField *TPURITMITM_INDICE;
	TWideStringField *TPURITMITM_NAME;
	TCurrencyField *TPURITMINVITM_AMOUNT;
	TLargeintField *TPURITMINVITM_QTY;
	TCurrencyField *TPURITMTotal;
	TWideStringField *TPURITMINVITM_COMMENT;
	TWideStringField *TPURITMINVITM_DELIVERY;
	TCurrencyField *TPURITMITM_PURCHASE;
	TFDQuery *WITM_NEXTIND;
	TWideStringField *WITM_NEXTINDITM_CP;
	TLargeintField *WITM_NEXTINDITM_CODE;
	TWideStringField *WITM_NEXTINDITM_INDICE;
	TFDQuery *VITM;
	TWideStringField *VITMITM_CP;
	TLargeintField *VITMITM_CODE;
	TWideStringField *VITMITM_INDICE;
	TWideStringField *VITMITM_NAME;
	TWideStringField *VITMITM_UNIT;
	TLargeintField *VITMStock;
	TWideStringField *VITMITM_COMMENT;
	TLargeintField *VITMITM_ID;
	TDataSource *DWINV;
	TFDQuery *QMOVPUR;
	TDataSource *DMOVPUR;
	TCurrencyField *TPURITMITM_SALE;
	TLargeintField *TPURITMPUR;
	TLargeintField *TPURITMSAL;
	TLargeintField *TPURITMLF;
	TLargeintField *TPURITMASM;
	TLargeintField *TPURITMUSED;
	TLargeintField *TPURITMStock;
	TLargeintField *TPURITMITM_GRP_ID;
	TWideStringField *TPURITMGRP_NAME;
	TCurrencyField *TPURITMProfit;
	TLargeintField *TSALITMPUR;
	TLargeintField *TSALITMSAL;
	TLargeintField *TSALITMLF;
	TLargeintField *TSALITMASM;
	TLargeintField *TSALITMUSED;
	TLargeintField *TSALITMStock;
	TLargeintField *TSALITMITM_GRP_ID;
	TWideStringField *TSALITMGRP_NAME;
	TFDQuery *QMOVSAL;
	TSQLTimeStampField *QMOVSALINV_DATE;
	TLargeintField *QMOVSALINV_NUMBER;
	TLargeintField *QMOVSALINVITM_QTY;
	TWideStringField *QMOVSALCNT_FIRSTNAME;
	TWideStringField *QMOVSALITM_CP;
	TLargeintField *QMOVSALITM_CODE;
	TWideStringField *QMOVSALITM_INDICE;
	TWideStringField *QMOVSALGRP_NAME;
	TWideStringField *QMOVSALITM_NAME;
	TCurrencyField *QMOVSALINVITM_AMOUNT;
	TCurrencyField *QMOVSALITM_PURCHASE;
	TCurrencyField *QMOVSALITM_SALE;
	TLargeintField *QMOVSALPUR;
	TLargeintField *QMOVSALSAL;
	TLargeintField *QMOVSALLF;
	TLargeintField *QMOVSALASM;
	TLargeintField *QMOVSALUSED;
	TLargeintField *QMOVSALStock;
	TWideStringField *QMOVSALITM_COMMENT;
	TWideStringField *QMOVSALINV_COMMENT;
	TWideStringField *QMOVSALINVITM_COMMENT;
	TLargeintField *QMOVSALITM_GRP_ID;
	TLargeintField *QMOVSALITM_ID;
	TLargeintField *QMOVSALINV_CNT_ID;
	TDataSource *DMOVSAL;
	TLargeintField *QMOVSALINV_ID;
	TFDQuery *TASM;
	TLargeintField *TASMASM_ID;
	TLargeintField *TASMASM_ITM_ID;
	TLargeintField *TASMASM_ITM_QTY;
	TDateField *TASMASM_DATE;
	TWideStringField *TASMASM_COMMENT;
	TWideStringField *TASMITM_CP;
	TLargeintField *TASMITM_CODE;
	TWideStringField *TASMITM_INDICE;
	TWideStringField *TASMITM_NAME;
	TCurrencyField *TASMITM_SALE;
	TLargeintField *TASMGRP_ID;
	TWideStringField *TASMGRP_NAME;
	TLargeintField *WASMASM_ID;
	TLargeintField *WASMASM_ITM_ID;
	TLargeintField *WASMASM_ITM_QTY;
	TDateField *WASMASM_DATE;
	TWideStringField *WASMASM_COMMENT;
	TFDQuery *CheckBAB;
	TCurrencyField *TSALITMTotal_Discount;
	TCurrencyField *TPURITMTotal_Gap;
	TCurrencyField *QMOVSALTotal_Discount;
	TFDQuery *PARAM;
	TLargeintField *TLFITMLFITM_QTY;
	TWideStringField *TLFITMLFITM_COMMENT;
	TSQLTimeStampField *TLFITMLFITM_DATE;
	TLargeintField *TLFITMLFITM_ID;
	TLargeintField *TLFITMLFITM_ITM_ID;
	TLargeintField *TLFITMLF;
	TLargeintField *WLFITMLFITM_ID;
	TLargeintField *WLFITMLFITM_LF_ID;
	TLargeintField *WLFITMLFITM_ITM_ID;
	TLargeintField *WLFITMLFITM_QTY;
	TSQLTimeStampField *WLFITMLFITM_DATE;
	TWideStringField *WLFITMLFITM_COMMENT;
	TSQLTimeStampField *QHSTITMLFLFITM_DATE;
	TLargeintField *QHSTITMLFLFITM_QTY;
	TWideStringField *QHSTITMLFLFITM_COMMENT;
	TDataSource *DLF;
	TFDQuery *TLF;
	TFDTable *WLF;
	TLargeintField *WLFLF_ID;
	TWideStringField *WLFLF_CATEGORY;
	TWideStringField *WLFLF_COMMENT;
	TWideStringField *TLFITMLF_CATEGORY;
	TLargeintField *TLFITMLF_ID;
	TFDQuery *WITMS;
	TLargeintField *WITMSITM_ID;
	TLargeintField *WITMSStock;
	TWideStringField *WITMSITM_CP;
	TLargeintField *WITMSPUR;
	TLargeintField *WITMSSAL;
	TLargeintField *WITMSLF;
	TLargeintField *WITMSASM;
	TLargeintField *WITMSUSED;
	TLargeintField *WITMSITM_CODE;
	TWideStringField *QHSTITMLFLF_CATEGORY;
	TFDQuery *TCNT;
	TFDQuery *TGRP;
	TLargeintField *TGRPGRP_ID;
	TWideStringField *TGRPGRP_NAME;
	TWideStringField *TGRPGRP_COMMENT;
	TLargeintField *QMOVSALINVITM_ID;
	TFDQuery *TPUR;
	TLargeintField *TPURINV_ID;
	TLargeintField *TPURINV_CNT_ID;
	TWideStringField *TPURINV_TYPE;
	TLargeintField *TPURINV_NUMBER;
	TWideStringField *TPURSupplier;
	TSQLTimeStampField *TPURINV_DATE;
	TCurrencyField *TPURTotal;
	TCurrencyField *TPURDue;
	TWideStringField *TPURINV_STATUS;
	TWideStringField *TPURINV_COMMENT;
	TFDQuery *TSAL;
	TLargeintField *TSALINV_ID;
	TLargeintField *TSALINV_CNT_ID;
	TWideStringField *TSALINV_TYPE;
	TLargeintField *TSALINV_NUMBER;
	TWideStringField *TSALClient;
	TSQLTimeStampField *TSALINV_DATE;
	TCurrencyField *TSALTotal;
	TCurrencyField *TSALDue;
	TWideStringField *TSALINV_STATUS;
	TWideStringField *TSALINV_COMMENT;
	TWideStringField *PARAMNAME;
	TWideStringField *PARAMValue;
	TLargeintField *TCNTCNT_ID;
	TWideStringField *TCNTCNT_FIRSTNAME;
	TWideStringField *TCNTCNT_PHONE;
	TWideStringField *TCNTCNT_EMAIL;
	TWideStringField *TCNTCNT_ADDRESS;
	TWideStringField *TCNTCNT_COMMENT;
	TLargeintField *WCNTCNT_ID;
	TWideStringField *WCNTCNT_FIRSTNAME;
	TWideStringField *WCNTCNT_PHONE;
	TWideStringField *WCNTCNT_EMAIL;
	TWideStringField *WCNTCNT_ADDRESS;
	TWideStringField *WCNTCNT_COMMENT;
	TDataSource *DPARAM;
	TFDTable *WSALITM;
	TLargeintField *WSALITMINVITM_ID;
	TLargeintField *WSALITMINVITM_INV_ID;
	TLargeintField *WSALITMINVITM_ITM_ID;
	TLargeintField *WSALITMITM_GRP_ID;
	TWideStringField *WSALITMGRP_NAME;
	TWideStringField *WSALITMITM_CP;
	TLargeintField *WSALITMITM_CODE;
	TWideStringField *WSALITMITM_INDICE;
	TCurrencyField *WSALITMINVITM_AMOUNT;
	TLargeintField *WSALITMINVITM_QTY;
	TCurrencyField *WSALITMTotal;
	TWideStringField *WSALITMINVITM_COMMENT;
	TWideStringField *WSALITMINVITM_DELIVERY;
	TCurrencyField *WSALITMITM_PURCHASE;
	TWideStringField *WSALITMITM_NAME;
	TCurrencyField *WSALITMITM_SALE;
	TLargeintField *WSALITMPUR;
	TLargeintField *WSALITMSAL;
	TLargeintField *WSALITMLF;
	TLargeintField *WSALITMASM;
	TLargeintField *WSALITMUSED;
	TLargeintField *WSALITMStock;
	TCurrencyField *WSALITMProfit;
	TWideStringField *WSALITMITM_COMMENT;
	TDataSource *DMEMOINFO;
	TFDTable *MEMOINFO;
	TWideStringField *MEMOINFOMemoName;
	TMemoField *MEMOINFOMemo;
	TWideStringField *QHSTITMSALINV_STATUS;
	TWideStringField *QHSTITMPURINV_STATUS;
	TDataSource *DMEMOLOG;
	TFDQuery *MEMOLOG;
	TMemoField *MEMOLOGMemo;
	TDataSource *DQLFITMPUR;
	TFDQuery *QLFITMPUR;
	TLargeintField *QLFITMPURINVITM_INV_ID;
	TLargeintField *QLFITMPURITM_ID;
	TLargeintField *QLFITMPURINV_NUMBER;
	TWideStringField *QLFITMPURCNT_FIRSTNAME;
	TCurrencyField *QLFITMPURINVITM_AMOUNT;
	TLargeintField *QLFITMPURINVITM_QTY;
	TSQLTimeStampField *QLFITMPURINV_DATE;
	TWideStringField *QLFITMPURINV_STATUS;
	TFDQuery *QLFITMSAL;
	TDataSource *DQLFITMSAL;
	TLargeintField *QLFITMSALINVITM_INV_ID;
	TLargeintField *QLFITMSALITM_ID;
	TLargeintField *QLFITMSALINV_NUMBER;
	TWideStringField *QLFITMSALCNT_FIRSTNAME;
	TCurrencyField *QLFITMSALINVITM_AMOUNT;
	TLargeintField *QLFITMSALINVITM_QTY;
	TSQLTimeStampField *QLFITMSALINV_DATE;
	TWideStringField *QLFITMSALINV_STATUS;
	TLargeintField *QHSTITMFROMASMASM_ID;
	TLargeintField *QHSTITMLFLFITM_ID;
	TLargeintField *QHSTITMASMASMITM_ID;
	TWideStringField *QTODO_SALPAYCNT_PHONE;
	TWideStringField *QTODO_PURPAYCNT_PHONE;
	TWideStringField *QTODO_SALDLVCNT_PHONE;
	TWideStringField *QTODO_SALDLVCNT_ADDRESS;
	TWideStringField *QTODO_PURDLVCNT_PHONE;
	TWideStringField *QTODO_PURDLVCNT_ADDRESS;
	TFDQuery *QTODONEGERR;
	TDataSource *DTODONEGERR;
	TCurrencyField *QTODONEGERRErrDefPur;
	TCurrencyField *QTODONEGERRErrDefSal;
	TLargeintField *QTODO_NEGITM_ID;
	TWideStringField *QTODO_NEGITM_CP;
	TLargeintField *QTODO_NEGITM_CODE;
	TWideStringField *QTODO_NEGITM_INDICE;
	TWideStringField *QTODO_NEGITM_NAME;
	TLargeintField *QTODO_NEGQty;
	TCurrencyField *QTODO_NEGTotDefPur;
	TCurrencyField *QTODO_NEGTotDefSal;
	TWideStringField *QTODO_UNKITM_CP;
	TLargeintField *QTODO_UNKITM_CODE;
	TWideStringField *QTODO_UNKITM_INDICE;
	TWideStringField *QTODO_UNKITM_NAME;
	TLargeintField *QTODO_UNKQty;
	TCurrencyField *QTODO_UNKTotDefPur;
	TCurrencyField *QTODO_UNKTotDefSal;
	TLargeintField *QTODO_UNKITM_ID;
	TFDQuery *QTODOUNKERR;
	TCurrencyField *CurrencyField1;
	TCurrencyField *CurrencyField2;
	TDataSource *TODOUNKERR;
	TFDQuery *MEMOTODO;
	TMemoField *MemoField1;
	TDataSource *DMEMOTODO;
	TLargeintField *QTODO_SALDLVINV_ID;
	TLargeintField *QTODO_PURDLVINV_ID;
	TLargeintField *QTODO_SALPAYINV_ID;
	TLargeintField *QTODO_PURPAYINV_ID;
	TLargeintField *QTODO_PURDLVINV_NUMBER;
	TSQLTimeStampField *QTODO_PURDLVINV_DATE;
	TLargeintField *QTODO_SALDLVINV_NUMBER;
	TSQLTimeStampField *QTODO_SALDLVINV_DATE;
	TLargeintField *QTODO_PURDLVITM_ID;
	TLargeintField *QTODO_SALDLVITM_ID;
	TSQLTimeStampField *QMOVPURINV_DATE;
	TLargeintField *QMOVPURINV_NUMBER;
	TWideStringField *QMOVPURCNT_FIRSTNAME;
	TLargeintField *QMOVPURITM_CODE;
	TWideStringField *QMOVPURITM_INDICE;
	TWideStringField *QMOVPURGRP_NAME;
	TLargeintField *QMOVPURINVITM_QTY;
	TCurrencyField *QMOVPURINVITM_AMOUNT;
	TCurrencyField *QMOVPURTotal_Gap;
	TCurrencyField *QMOVPURITM_PURCHASE;
	TCurrencyField *QMOVPURITM_SALE;
	TLargeintField *QMOVPURPUR;
	TLargeintField *QMOVPURSAL;
	TLargeintField *QMOVPURLF;
	TLargeintField *QMOVPURASM;
	TLargeintField *QMOVPURUSED;
	TLargeintField *QMOVPURStock;
	TWideStringField *QMOVPURITM_COMMENT;
	TWideStringField *QMOVPURINV_COMMENT;
	TWideStringField *QMOVPURINVITM_COMMENT;
	TLargeintField *QMOVPURITM_GRP_ID;
	TLargeintField *QMOVPURINV_CNT_ID;
	TLargeintField *QMOVPURITM_ID;
	TLargeintField *QMOVPURINV_ID;
	TLargeintField *QMOVPURINVITM_ID;
	TWideStringField *QMOVPURITM_CP;
	TWideStringField *QMOVPURITM_NAME;
	TFDQuery *TPURPAY;
	TLargeintField *TPURPAYINVPAY_ID;
	TCurrencyField *TPURPAYINVPAY_AMOUNT;
	TSQLTimeStampField *TPURPAYINVPAY_DATE;
	TWideStringField *TPURPAYINVPAY_COMMENT;
	TLargeintField *TPURPAYINVPAY_INV_ID;
	TSQLTimeStampField *TPURINV_LOCKDATE;
	TSQLTimeStampField *TSALINV_LOCKDATE;
	TSQLTimeStampField *WINVINV_LOCKDATE;
	TLargeintField *TLFLF_ID;
	TWideStringField *TLFLF_CATEGORY;
	TWideStringField *TLFLF_COMMENT;

	void __fastcall DGRPDataChange(TObject *Sender, TField *Field);
	void __fastcall TITMBeforeDelete(TDataSet *DataSet);
	void __fastcall TPURITMBeforeDelete(TDataSet *DataSet);
	void __fastcall TPURPAYBeforeDelete(TDataSet *DataSet);
	void __fastcall DPURITMDataChange(TObject *Sender, TField *Field);
	void __fastcall DITMDataChange(TObject *Sender, TField *Field);
	void __fastcall DHSTITMPURDataChange(TObject *Sender, TField *Field);
	void __fastcall TLFITMAfterDelete(TDataSet *DataSet);
	void __fastcall TPURBeforeDelete(TDataSet *DataSet);
	void __fastcall DCNTDataChange(TObject *Sender, TField *Field);
	void __fastcall TSALITMBeforeDelete(TDataSet *DataSet);
	void __fastcall TSALPAYBeforeDelete(TDataSet *DataSet);
	void __fastcall TSALBeforeDelete(TDataSet *DataSet);
	void __fastcall DSALITMDataChange(TObject *Sender, TField *Field);
	void __fastcall TASMITMBeforeDelete(TDataSet *DataSet);
	void __fastcall TPURITMBeforeInsert(TDataSet *DataSet);
	void __fastcall TPURITMBeforeEdit(TDataSet *DataSet);
	void __fastcall TPURBeforeEdit(TDataSet *DataSet);
	void __fastcall TPURBeforeInsert(TDataSet *DataSet);
	void __fastcall TSALBeforeEdit(TDataSet *DataSet);
	void __fastcall TSALBeforeInsert(TDataSet *DataSet);
	void __fastcall TSALITMBeforeEdit(TDataSet *DataSet);
	void __fastcall TSALITMBeforeInsert(TDataSet *DataSet);
	void __fastcall TITMBeforeEdit(TDataSet *DataSet);
	void __fastcall DPURDataChange(TObject *Sender, TField *Field);
	void __fastcall DSALDataChange(TObject *Sender, TField *Field);
	void __fastcall DLFITMDataChange(TObject *Sender, TField *Field);
	void __fastcall DASMITMDataChange(TObject *Sender, TField *Field);
	void __fastcall TGRPBeforeDelete(TDataSet *DataSet);
	void __fastcall TCNTBeforeDelete(TDataSet *DataSet);
	void __fastcall TLFITMBeforeInsert(TDataSet *DataSet);
	void __fastcall TASMITMBeforeInsert(TDataSet *DataSet);
	void __fastcall DMOVPURDataChange(TObject *Sender, TField *Field);
	void __fastcall DMOVSALDataChange(TObject *Sender, TField *Field);
	void __fastcall DLFDataChange(TObject *Sender, TField *Field);
	void __fastcall TLFBeforeEdit(TDataSet *DataSet);
	void __fastcall TLFBeforeDelete(TDataSet *DataSet);
	void __fastcall TLFITMBeforeEdit(TDataSet *DataSet);
	void __fastcall TCNTBeforeEdit(TDataSet *DataSet);
	void __fastcall TGRPBeforeEdit(TDataSet *DataSet);
	void __fastcall TLFITMBeforeDelete(TDataSet *DataSet);
	void __fastcall TASMBeforeDelete(TDataSet *DataSet);
	void __fastcall TCNTBeforeInsert(TDataSet *DataSet);
	void __fastcall TGRPBeforeInsert(TDataSet *DataSet);
	void __fastcall TLFBeforeInsert(TDataSet *DataSet);
	void __fastcall TASMBeforeInsert(TDataSet *DataSet);
	void __fastcall TASMBeforeEdit(TDataSet *DataSet);
	void __fastcall TASMITMBeforeEdit(TDataSet *DataSet);
	void __fastcall DSTODO_NEGDataChange(TObject *Sender, TField *Field);
	void __fastcall DSTODO_UNKDataChange(TObject *Sender, TField *Field);
private:      // Déclarations utilisateur

	bool __fastcall LFWriteAccess(void);
	bool __fastcall LFITMWriteAccess(int itmid);
public:       // Déclarations utilisateur

	int LFID_SaleWithoutCode;
	int LFID_SaleNegativeItem;
	int LFID_ItemLostOrFound;

				__fastcall TDM(TComponent* Owner);

  void 			__fastcall ClearLog(void);
  void 			__fastcall SQL_ITM(UnicodeString txt);
  void 			__fastcall SQL_MOVPUR(UnicodeString txt);
  void 			__fastcall SQL_MOVSAL(UnicodeString txt);
  void 			__fastcall LogAdd(UnicodeString txt);
  void 			__fastcall UpdateTreeViewLog(void);
  void 			__fastcall DatabaseOpen(void);
  void 			__fastcall DatabaseClose(void);
  bool 			__fastcall DatabaseExist(void);
  void 			__fastcall DatabaseVersion(void);
  void 			__fastcall DatabaseTableOpen(void);
  UnicodeString __fastcall GetDBParam(UnicodeString param);
  void 			__fastcall SetDBParam(UnicodeString param, UnicodeString value);
  void 			__fastcall MasterClose(void);
  void 			__fastcall MasterOpen(void);

  void 			__fastcall DisableCtrl(void);
  void 			__fastcall EnableCtrl(void);
  void 			__fastcall RefreshQ(TFDQuery *query, UnicodeString key, int id);
  void 			__fastcall RefreshT(TFDTable *table, UnicodeString key, int id) ;
  void 			__fastcall RefreshCNT(int id);
  void 			__fastcall RefreshGRP(int id);
  void 			__fastcall RefreshITM(int id);
  void 			__fastcall RefreshPUR(int id);
  void 			__fastcall RefreshPURITM(int id);
  void 			__fastcall RefreshPURPAY(int id);
  void 			__fastcall RefreshSAL(int id);
  void 			__fastcall RefreshSALITM(int id);
  void 			__fastcall RefreshSALPAY(int id);
  void 			__fastcall RefreshLFITM(int id);
  void 			__fastcall RefreshMOVPUR(int id);
  void 			__fastcall RefreshMOVSAL(int id);
  void 			__fastcall RefreshASM(int id);
  void 			__fastcall RefreshASMITM(int id);
  void 			__fastcall RefreshHST(void);
  void 			__fastcall RefreshAll(void);

  bool 			__fastcall UpdateSystemLFITM(int itmid);
  void 			__fastcall NegativeStockCompens(void);
  void 			__fastcall TryRemoveITM(int itmid);

  void          __fastcall UpdateINV(TFDQuery *inv, TDateTime date);
  UnicodeString __fastcall GetINVStatus(int due, int total, int itemcount);
  void 			__fastcall WPURITMInsert(int purid, int itmid, int qty, double amount);
  void 			__fastcall WSALITMInsert(int salid, int itmid, int qty, double amount);
  void 			__fastcall WASMITMInsert(int asmid, int itmid, int qty);
  bool 			__fastcall IsDigit(UnicodeString txt);

protected:
__published:
};

extern PACKAGE TDM *DM;

#endif

